# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-07 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reg',
            name='name',
        ),
        migrations.AddField(
            model_name='reg',
            name='contact_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reg',
            name='email',
            field=models.EmailField(help_text='Required', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='reg',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reg',
            name='firstname',
            field=models.CharField(help_text='Required', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='reg',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reg',
            name='lastname',
            field=models.CharField(help_text='Required', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='reg',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reg',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reg',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reg',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='reg',
            name='username',
            field=models.CharField(help_text='Required', max_length=250, null=True),
        ),
    ]
