# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-07 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20190607_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='Fname',
            field=models.CharField(help_text='Required', max_length=250, null=True),
        ),
    ]
